### PR TITLE
Cleanup updates

### PR DESCRIPTION
**Pull request by teghnet**

### CODE REVIEW

**Comment by adshares-tech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [Serialize.php#L35](https://github.com/adshares/adserver/blob/f8b67205fc069988db4f808a814ec341a29a4567/app/Models/Traits/Serialize.php#L35): Make sure deserializing objects is safe here. [rule](https://sonarcloud.io/coding_rules#rule_key=php%3AS4508)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'

**Comment by adshares-tech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [Serialize.php#L35](https://github.com/adshares/adserver/blob/7c55e411e6d9c5902710aec709cf6ae9f02d5d12/app/Models/Traits/Serialize.php#L35): Make sure deserializing objects is safe here. [rule](https://sonarcloud.io/coding_rules#rule_key=php%3AS4508)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'

**Comment by adshares-tech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [Serialize.php#L35](https://github.com/adshares/adserver/blob/72f1deeaeddaef6d4b1fe04502b62ae6415f61dd/app/Models/Traits/Serialize.php#L35): Make sure deserializing objects is safe here. [rule](https://sonarcloud.io/coding_rules#rule_key=php%3AS4508)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'

**Comment by adshares-tech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [Serialize.php#L35](https://github.com/adshares/adserver/blob/5cf93c7c67348aa106c1e3989be74a42f24e9513/app/Models/Traits/Serialize.php#L35): Make sure deserializing objects is safe here. [rule](https://sonarcloud.io/coding_rules#rule_key=php%3AS4508)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'

**Review by michaldzwigala — APPROVED** [review]

**Pull request merged**
